-
  version: 1.0.{build}
  branches:
    except:
    - v1.1.x
    - v1.2.x
    - v1.3.x
  skip_tags: true
  image: Visual Studio 2017
  environment:
    matrix:
    - nodejs_version: Stable
      vs_version: 15.0
      architecture: x64
  install: &default_install_script
    - ps: >-
        Install-Product node $env:nodejs_version $env:architecture

        node -v

        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"

        $node = which node

        $node = $node.Replace("/c/", "C:\").Replace("/", "\") + ".exe"

        echo $node

        netsh advfirewall firewall add rule name="Nodejs" dir=in action=allow program="$node" enable=yes
  build_script: &default_build_script
    - ps: >-
        regedit /s c:\projects\nodejstools\Nodejs\Prerequisites\EnableSkipVerification.reg

        msiexec /package C:\projects\nodejstools\Common\Tests\Prerequisites\VSTestHost.msi /quiet

        c:\projects\nodejstools\Nodejs\.nuget\nuget.exe restore "c:\projects\nodejstools\Nodejs\NodejsTools.sln" -PackagesDirectory c:\projects\nodejstools\Nodejs\packages -ConfigFile c:\projects\nodejstools\Nodejs\.nuget\appveyor.Config

        C:\projects\nodejstools\Nodejs\Setup\BuildRelease.ps1 .\NTVS_Out -skipcopy -skipdebug -skipclean -skiptests -vsTarget $env:vs_version -vsroot "$(${env:programfiles(x86)} + "\Microsoft Visual Studio\2017\Community")"
  artifacts: &default_artifacts
    - path: NTVS_Out
      name: NtvsOut
      type: zip